local BM_Utils = require('BM_Utils')

Events.OnLoadedTileDefinitions.Add(function(manager)
    BM_Utils.setOrUnsetSpriteProperties(manager, {
        "en_newburbs_windows_01_0",
        "en_newburbs_windows_01_8",
        "en_newburbs_windows_01_16",
        "en_newburbs_windows_01_17",
        "en_newburbs_windows_01_18",
        "en_newburbs_windows_01_19",
        "en_newburbs_windows_01_48",
        "en_newburbs_windows_01_49",
        "en_newburbs_windows_01_50",
        "en_newburbs_windows_01_51",
        "en_newburbs_windows_01_80",
        "en_newburbs_windows_01_81",
        "en_newburbs_windows_01_82",
    }, {
        { "CanBreak",           "",        false },
        { "CustomName",         "Window",  false },
        { "GroupName",          "Wooden",  false },
        { "Facing",             "W",       false },
        { "IsClosedState",      "",        false },
        { "IsMoveAble",         "",        false },
        { "MoveType",           "Window",  false },
        { "Noffset",            "1",       false },
        { "PickUpLevel",        "2",       false },
        { "PickUpTool",         "Crowbar", false },
        { "PickUpWeight",       "100",     false },
        { "PlaceTool",          "Hammer",  false },
        { "WindowN",            "WindowN", false },
        { "disableFade",        "",        false },
        { IsoFlagType.attachedW },
    }, nil);

    BM_Utils.setOrUnsetSpriteProperties(manager, {
        "en_newburbs_windows_01_4",
        "en_newburbs_windows_01_12",
        "en_newburbs_windows_01_20",
        "en_newburbs_windows_01_21",
        "en_newburbs_windows_01_22",
        "en_newburbs_windows_01_23",
        "en_newburbs_windows_01_52",
        "en_newburbs_windows_01_53",
        "en_newburbs_windows_01_54",
        "en_newburbs_windows_01_55",
        "en_newburbs_windows_01_84",
        "en_newburbs_windows_01_85",
        "en_newburbs_windows_01_86",
    }, {
        { "CanBreak",           "",        false },
        { "CustomName",         "Window",  false },
        { "GroupName",          "Wooden",  false },
        { "Facing",             "N",       false },
        { "IsClosedState",      "",        false },
        { "IsMoveAble",         "",        false },
        { "MoveType",           "Window",  false },
        { "Woffset",            "-1",      false },
        { "PickUpLevel",        "2",       false },
        { "PickUpTool",         "Crowbar", false },
        { "PickUpWeight",       "100",     false },
        { "PlaceTool",          "Hammer",  false },
        { "WindowN",            "WindowN", false },
        { "disableFade",        "",        false },
        { IsoFlagType.attachedN },
    }, nil);
end)
